defaults: &defaults
  docker:
    - image: circleci/node:10

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install & npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - packages
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint
  bundlesize:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run bundlesize
  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat coverage/lcov.info | npx coveralls
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: git config user.name "Circle CI"
      - run: git config user.email "circleci@circleci.com"
      - run: npm run release

workflows:
  version: 2
  test-build-publish:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - bundlesize:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only:
                - master