defaults: &defaults
  docker:
    - image: circleci/node:10

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install & npx lerna bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - packages
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - coverage
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run eslint
  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat coverage/lcov.info | npx coveralls
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npx lerna publish

workflows:
  version: 2
  test-build-publish:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - lint
            - test
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/